name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Update system
      run: sudo apt update -y
    - name: Install libev
      run: sudo apt install -y libev4 libev-dev
    - name: Install gcc-9
      run: sudo apt install -y gcc-9
    - name: Install systemd
      run: sudo apt install -y libsystemd-dev
    - name: Install rst2man
      run: sudo apt install -y python-docutils
    - name: Install zstd
      run: sudo apt install -y libzstd-dev
    - name: Install lz4
      run: sudo apt install -y liblz4-dev
    - name: Update alternatives
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60
    - name: mkdir
      run: mkdir build
      working-directory: /home/runner/work/pgmoneta/pgmoneta/
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
    - name: make
      run: make
      working-directory: /home/runner/work/pgmoneta/pgmoneta/build/
